Fail institution edit form validation if an iA.Delib category is mapp…
IMIO/plonemeeting.portal.core pull request #33
Opened 2021-08-18 12:57 UTC by odelaere

…ed multiple times #PM-3465

2021-08-20 09:12 UTC, gbastien requested changes
@odelaere testé dans l'interface, çà fonctionne, juste message de validation non traduit

2021-08-20 09:12 UTC, gbastien commented on src/plonemeeting/portal/core/content/institution.py
> +from zope.interface import Interface, invariant, Invalid
@odelaere 
1 import par ligne

2021-08-20 09:12 UTC, gbastien commented on src/plonemeeting/portal/core/content/institution.py
> +            raise Invalid("{}: {}".format(_(u'iA.Delib category mapped more than once'),
le msgid "iA.Delib category mapped more than once" n'est pas traduit, tu dois utiliser le paramètre "mapping" si tu souhaites passer des valeurs dans la traduction:
`_(u'iA.Delib category mapped more than once'), mapping={'categories_title': ', '.join(...))` et dans le msgstr tu réutilises `categories_title` sous la forme `${categories_title}`

2021-08-20 09:12 UTC, gbastien commented on src/plonemeeting/portal/core/tests/test_browser_institution.py
> +
saut de ligne inutile?

2021-08-20 12:53 UTC, gbastien requested changes

2021-08-20 12:53 UTC, gbastien commented on src/plonemeeting/portal/core/content/institution.py
> +                                    target_language=api.portal.get_default_language()[:2],
Définir le target_language n'est pas utile, en l'enlevant çà fonctionne dans l'interface et les tests

2021-08-20 12:53 UTC, gbastien commented on src/plonemeeting/portal/core/locales/fr/LC_MESSAGES/plonemeeting.portal.core.po
> +msgstr "Catégorie iA.Delib renseignée plusieurs fois : ${categories_title}"
Avec les invariants comme le message n'apparaît pas autour du champ problématique mais au dessus du form, j'ai pris l'habitude de répéter le nom du champ au début du message : `Correspondances des matières: des catégories iA.Délib sont sélectionnées plusieurs fois (...)`
C'est utile le jour où tu as plusieurs invariants pour plusieurs champs, ou 1 invariant pour plusieurs champs.
Ici c'est dommage qu'un form validator ne fonctionne pas

2021-08-20 12:53 UTC, gbastien commented on src/plonemeeting/portal/core/tests/test_browser_institution.py
> +        institution_edit_form = self.belleville.restrictedTraverse("@@edit")
est ce nécessaire de mettre le form dans la request?  essaie en enlevant tout ce qui est lié à l'edit_form? a priori invariant est lié à l'interface donc fonctionne sans le form et les valeurs lui sont passées directement

2021-08-23 09:22 UTC, odelaere commented on src/plonemeeting/portal/core/content/institution.py
> +                                    target_language=api.portal.get_default_language()[:2],
Qund jeretir ce param, on dirait qu'il essaie utiliser la langue du browser.
Donc chez moi, ça le met dans la "default"

![Amityville](https://user-images.githubusercontent.com/23073839/130423195-1d298f46-cd85-48f0-8a7c-77e6bba1d63a.png)

2021-08-23 11:34 UTC, merged