Query categories from iA.Delib to populate vocabularies only when loa…
IMIO/plonemeeting.portal.core pull request #37
Opened 2021-08-24 13:44 UTC by odelaere

…ding the edit form

2021-09-01 14:37 UTC, gbastien requested changes
OK l'implémentation est similaire de au fetch des catégories.
Dans l'interface peut-être, changer le titre de la colonne et limiter la largeur de la colonne ?
Un libellé du genre "Mandataire dans iA.Délib" me semble suffisant (sans plus de description)
![image](https://user-images.githubusercontent.com/1274924/131690941-3900b633-2c1b-4866-a288-a31341cc2658.png)

2021-09-01 14:37 UTC, gbastien commented on src/plonemeeting/portal/core/vocabularies.py
> +        req = getRequest()
Déplacer définition de "req" dans le "if" pour ne pas le définir pour rien dans certains cas

2021-09-03 14:59 UTC, gbastien requested changes
Erreur à l'accès à une institution existante:
`  Module plonemeeting.portal.core.vocabularies, line 116, in __call__
AttributeError: 'list' object has no attribute 'keys'`
Il manque une migration pour `delib_representatives`?  Dans la step vers 1006 je vois `delib_categories` qui est migré mais pas `delib_representatives`
Sinon çà semble fonctionner, j'ai testé localement et les mandataires sont bien fonctionnels...
Un peu de "isort" par ci par là aussi.
Et adapter le titre de la colonne "UID mandataire dans iA.Délib" pour "Mandataire dans iA.Délib"

2021-09-06 09:09 UTC, odelaere commented
delib_representatives c'est nouveau avec les changements de cette PR. à mon avis tu avais une version intermédiaire.
J'ai créé un site depuis le master.
Je l'ai ensuite migré dans cette branche.
Pas eu de soucis :/

2021-09-06 09:17 UTC, gbastien approved these changes
LGTM

2021-09-06 09:19 UTC, merged